env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 100
    lines: 25
  padding:
    x: 2
    y: 2
  dynamic_padding: true

  # Window title
  title: Alacritty
  dynamic_title: true

  # Window class
  class:
    # Application instance name
    instance: Alacritty
    # General application class
    general: Alacritty

scrolling:
  history: 10000

  # Line scrollback amount (history > 0).
  multiplier: 2

# Font configuration
font:
  # Normal (roman) font face
  normal:
    family: Terminus
  size: 10

  # Offset is the extra space around each character
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  #glyph_offset:
  #  x: 0
  #  y: 0

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

# Allow terminal applications to change Alacritty's window title.
  dynamic_title: true

cursor:
  style:
# Values for `shape`:
#   - ▇ Block
#   - _ Underline
#   - | Beam
    shape: Block
    blinking: Always

# If this is `true`, the cursor will be rendered as a hollow box when the window is unfocused
  unfocused_hollow: true

# Live config reload
live_config_reload: true

# Keybindings
key_bindings:
  - { key: C,		mods: Alt,          action: Copy             }
  - { key: V,		mods: Alt,          action: Paste            }
  - { key: K,		mods: Alt,          action: ScrollLineUp	 }
  - { key: J,   	mods: Alt,          action: ScrollLineDown   }
  - { key: K,		mods: Alt|Shift,    action: IncreaseFontSize }
  - { key: J,   	mods: Alt|Shift,    action: DecreaseFontSize }

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

# Background transparency
background_opacity: 0.9

